// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7goKcvuT25wEDjRII3j6uy9x5fAdN114',
    appId: '1:353763155584:web:a51fc75d336d5036d1d065',
    messagingSenderId: '353763155584',
    projectId: 'firbaselogin-f1adf',
    authDomain: 'firbaselogin-f1adf.firebaseapp.com',
    storageBucket: 'firbaselogin-f1adf.appspot.com',
    measurementId: 'G-7TVYJWH6HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6owNq2taO4mTmNxIYj6UVhVIEZQ6Uobw',
    appId: '1:353763155584:android:ed90af25f38eb698d1d065',
    messagingSenderId: '353763155584',
    projectId: 'firbaselogin-f1adf',
    storageBucket: 'firbaselogin-f1adf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMIQe-GjKeavK0yCtqWwd8ZYbzHuClawk',
    appId: '1:353763155584:ios:ef4ee4fdf23c1c90d1d065',
    messagingSenderId: '353763155584',
    projectId: 'firbaselogin-f1adf',
    storageBucket: 'firbaselogin-f1adf.appspot.com',
    iosClientId: '353763155584-gcatnokvuqdu05kfchci7u8out8m443b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMIQe-GjKeavK0yCtqWwd8ZYbzHuClawk',
    appId: '1:353763155584:ios:ef4ee4fdf23c1c90d1d065',
    messagingSenderId: '353763155584',
    projectId: 'firbaselogin-f1adf',
    storageBucket: 'firbaselogin-f1adf.appspot.com',
    iosClientId: '353763155584-gcatnokvuqdu05kfchci7u8out8m443b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBaseLogin',
  );
}
